usb_sniffer: fixed trying to write rst update when sniffer is not enabled
Previous behaviour before this fix has two consequences:

1. First cell in memory is filled without cfg_enabled.
2. Since after that write_detect_q is on then it causes buffer_full_q on
   without cfg_enabled. Later after sniffer enabling we get buffer_full_clr_w
   and next_addr_q jumps over cell with address 4. It means that we always
   get:

ERROR: Unknown ID 0 position 4